const BASE_BACKEND_URL='http://localhost:3001/'
const FALE_CONOSCO_EMAIL='aleksvp@gmail.com'
const ERROR_SESSION_EXPIRED=440

export {
    BASE_BACKEND_URL, FALE_CONOSCO_EMAIL, ERROR_SESSION_EXPIRED
}