function listarColunas(){
    return [
        {
          text: 'EMPRESA',
          align: 'start',
          value: 'empresa',
        },
        { text: 'CURSO', value: 'curso' },
        { text: 'OCUPAÇÕES RELACIONADAS', value: 'ocupacoes' },
        { text: 'DURAÇÃO(H)', value: 'duracao' },
        { text: 'CERTIFICADO', value: 'sncertificado' },
        { text: 'LÍNGUA', value: 'lingua'},
        { text: 'LINK', value: 'link', sortable: false },
      ]
}

function listarCursos(){
    return  [
        {
        empresa: 'Udemy',
        curso: 'Introdução à linguagem Python',
        ocupacoes: 'Programador de internet',
        duracao: 2,
        sncertificado: 'Sim',
        link: 'https://www.udemy.com/course/intro_python/',
        },
        {
            empresa: 'Udemy',
            curso: 'Photoshop CC 2019, Essencial, Rápido e Prático',
            ocupacoes: 'Desenhista de páginas da internet (web designer)',
            duracao: 4,
            sncertificado: 'Sim',
            link: 'https://www.udemy.com/course/photoshop-cc-essencial-rapido-e-pratico_photoshop/',
        },
        {
            empresa: 'Udemy',
            curso: 'Introdução à linguagem Python',
            ocupacoes: 'Programador de internet, Analista de sistemas, Analista de sistemas web',
            duracao: 2,
            sncertificado: 'Sim',
            link: 'https://www.udemy.com/course/intro_python/',
        },
        {
            empresa: 'Udemy',
            curso: 'O guia Completo do Marketing Digital',
            ocupacoes: 'Analista de Marketing, Administrador de Marketing, Gerente de Marketing',
            duracao: 24,
            sncertificado: 'Sim',
            link: 'https://www.udemy.com/course/marketing-digital-de-alta-conversao-completo-30-cursos-em-1/',
        },
        {
            empresa: 'Udemy',
            curso: 'Java para totalmente principiantes',
            ocupacoes: 'Programador de internet, Analista de sistemas, Analista de sistemas web',
            duracao: 18,
            sncertificado: 'Sim',
            link: 'https://www.udemy.com/course/fundamentos-java-para-principiantes-java-13-jdk-netbeans/',
        },
        {
            empresa: 'Fundação Bradesco',
            curso: 'Empreendedorismo e Inovação',
            ocupacoes: 'Administrador, Administrador de Empresas',
            duracao: 12,
            sncertificado: 'Sim',
            link: 'https://www.ev.org.br/curso/administracao/fundamentos-da-administracao/empreendedorismo-e-inovacao?return=/cursos/administracao&cst=490',
        },
        {
            empresa: 'Fundação Bradesco',
            curso: 'Introdução à Administração',
            ocupacoes: 'Administrador, Administrador de Empresas, Administrador de Marketing',
            duracao: 12,
            sncertificado: 'Sim',
            link: 'https://www.ev.org.br/curso/administracao/fundamentos-da-administracao/introducao-a-administracao?return=/cursos/administracao&cst=510',
        },
        {
            empresa: 'Fundação Bradesco',
            curso: 'Língua Portuguesa sem Complicações',
            ocupacoes: 'Professor de língua portuguesa',
            duracao: 20,
            sncertificado: 'Sim',
            link: 'https://www.ev.org.br/curso/educacao-basica-e-pedagogia/apoio-a-estudantes/lingua-portuguesa-sem-complicacoes?return=/cursos/educacao-basica-e-pedagogia&cst=430',
        },
        {
            empresa: 'Fundação Bradesco',
            curso: 'Técnicas de Redação',
            ocupacoes: 'Professor de língua portuguesa',
            duracao: 10,
            sncertificado: 'Sim',
            link: 'https://www.ev.org.br/curso/educacao-basica-e-pedagogia/apoio-a-estudantes/tecnicas-de-redacao?return=/cursos/educacao-basica-e-pedagogia&cst=345',
        },
        {
            empresa: 'Fundação Bradesco',
            curso: 'Análise de Balanços',
            ocupacoes: 'Assistente de contador de custos, Contador, Administrador',
            duracao: 20,
            sncertificado: 'Sim',
            link: 'https://www.ev.org.br/curso/contabilidade-e-financas/analise-de-balancos?return=/cursos/contabilidade-e-financas&cst=492',
        },
        {
            empresa: 'FBV',
            curso: 'Cuidador Infantil',
            ocupacoes: 'Cuidadores de crianças, jovens, adultos e idosos, Babá, Monitor infantil',
            duracao: '280',
            sncertificado: 'Sim, mas pago',
            link: 'https://www.fbvcursos.com/curso/curso-gratuito-online-cuidador-infantil',
        },
        {
            empresa: 'FBV',
            curso: 'Controle Integrado de pragas',
            ocupacoes: 'Controlador de pragas',
            duracao: '280',
            sncertificado: 'Sim, mas pago',
            link: 'https://www.fbvcursos.com/curso/curso-gratuito-online-controle-integrado-de-pragas',
        },
        {
            empresa: 'FBV',
            curso: 'Hidroponia',
            ocupacoes: 'Agricultor polivalente - conta própria, Agricultor familiar polivalente',
            duracao: '280',
            sncertificado: 'Sim, mas pago',
            link: 'https://www.fbvcursos.com/curso/curso-gratuito-de-hidroponia',
        },
        {
            empresa: 'FBV',
            curso: 'Nutrição básica',
            ocupacoes: 'Auxiliar de nutrição e dietética, Nutricionista, Técnico em nutrição',
            duracao: '280',
            sncertificado: 'Sim, mas pago',
            link: 'https://www.fbvcursos.com/curso/curso-gratuito-online-nutricao-basica',
        },
        {
            empresa: 'FBV',
            curso: 'Ecoturismo',
            ocupacoes: 'Condutor de turismo de aventura, Consultor em turismo (turismólogo)',
            duracao: '280',
            sncertificado: 'Sim, mas pago',
            link: 'https://www.fbvcursos.com/curso/curso-gratuito-online-ecoturismo',
        },
        {
            empresa: 'Prime Cursos',
            curso: 'Motorista de aplicativo',
            ocupacoes: 'Motorista',
            duracao: '15',
            sncertificado: 'Sim',
            link: 'https://www.primecursos.com.br/motorista-de-aplicativo/',
        },        
        {
            empresa: 'Prime Cursos',
            curso: 'Curso de Auxiliar de Veterinário e Pet Shop',
            ocupacoes: 'Auxiliar de veterinário, Atendente de consultório veterinário',
            duracao: '45',
            sncertificado: 'Sim',
            link: 'https://www.primecursos.com.br/auxiliar-de-veterinario-e-pet-shop-basico/',
        },        
        {
            empresa: 'Prime Cursos',
            curso: 'Telefonista',
            ocupacoes: 'Telefonista, Recepcionista telefonista, Telefonista-monitor, Atendente de telemarketing',
            duracao: '30',
            sncertificado: 'Sim',
            link: 'https://www.primecursos.com.br/telefonista/',
        },        
        {
            empresa: 'Prime Cursos',
            curso: 'Agricultura Orgânica',
            ocupacoes: 'Agricultor familiar polivalente. Agricultor polivalente - conta própria',
            duracao: '35',
            sncertificado: 'Sim',
            link: 'https://www.primecursos.com.br/agricultura-organica/',
        },        
        {
            empresa: 'Prime Cursos',
            curso: 'Agente Comunitário de Saúde',
            ocupacoes: 'Agente comunitário de saúde, Agente de saúde, Agente indígena de saúde',
            duracao: '30',
            sncertificado: 'Sim',
            link: 'https://www.primecursos.com.br/agente-comunitario-de-saude/',
        },    
        {
            empresa: 'Harvard',
            curso: 'Statistics and R',
            ocupacoes: 'Auxiliar de estatística, Estatístico',
            duracao: '16',
            sncertificado: 'Sim, mas pago',
            lingua: 'Inglesa',
            link: 'https://www.edx.org/course/statistics-and-r',
        },  
        {
            empresa: 'Harvard',
            curso: 'CS50s Introduction to Game Development',
            ocupacoes: 'Programador, Desenvolvedor de jogos',
            duracao: '100',
            sncertificado: 'Sim, mas pago',
            lingua: 'Inglesa',
            link: 'https://www.edx.org/course/cs50s-introduction-to-game-development',
        },            
    ]
}

export {
    listarCursos, listarColunas
}